# Generated by Django 5.2.1 on 2025-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'оборудования',
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='lesson_planner.equipment', verbose_name='Оборудование'),
        ),
    ]
