# Generated by Django 5.2.1 on 2025-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0002_equipment_lessonplan_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomteacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Отчество'),
        ),
    ]
