# Generated by Django 5.2.1 on 2025-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0003_classroomteacher_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='classroom_teacher',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=70, null=True, verbose_name='Отчество')),
                ('subjects', models.ManyToManyField(to='lesson_planner.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['last_name'],
            },
        ),
        migrations.DeleteModel(
            name='ClassroomTeacher',
        ),
    ]
