# Generated by Django 5.2.1 on 2025-06-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0004_remove_grade_classroom_teacher_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'оборудование'},
        ),
    ]
