# Generated by Django 5.2.1 on 2025-06-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0005_alter_equipment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='lesson_planner.lessontype')),
            ],
            options={
                'verbose_name': 'Этап шаблона',
                'verbose_name_plural': 'Этапы шаблонов',
                'ordering': ['lesson_type', 'order'],
            },
        ),
    ]
