# Generated by Django 5.2.1 on 2025-06-08 07:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0006_lessonsteptemplate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lessonsteptemplate',
            managers=[
                ('object_step', django.db.models.manager.Manager()),
            ],
        ),
    ]
