# Generated by Django 5.2.1 on 2025-06-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0007_alter_lessonsteptemplate_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Выберите оборудование', null=True, to='lesson_planner.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='goal',
            field=models.TextField(blank=True, help_text='Введите цель урока', verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Выберите класс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson_planner.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(help_text='Выберите предмет', on_delete=django.db.models.deletion.CASCADE, to='lesson_planner.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='subject_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип урока', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson_planner.lessontype', verbose_name='Тип урока'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='topic',
            field=models.CharField(help_text='Введите тему урока', max_length=300, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='lessonsteptemplate',
            name='order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Ведите название предмета', max_length=100, unique=True, verbose_name='Название предмета'),
        ),
    ]
