# Generated by Django 5.2.1 on 2025-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0008_alter_lessonplan_equipment_alter_lessonplan_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsteptemplate',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
    ]
