# Generated by Django 5.2.1 on 2025-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0009_alter_lessonsteptemplate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsteptemplate',
            name='name',
            field=models.CharField(help_text='Введите название этапа', max_length=200, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='lessonsteptemplate',
            name='order',
            field=models.PositiveIntegerField(help_text='Введите порядковый номер этапа', verbose_name='Порядок'),
        ),
    ]
