# Generated by Django 5.2.1 on 2025-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0015_lessontype_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип урока'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Ведите название предмета', max_length=100, verbose_name='Название предмета'),
        ),
    ]
