# Generated by Django 5.2.1 on 2025-06-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_planner', '0016_alter_grade_name_alter_lessontype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
